services:
  ping:
    build: .
    container_name: ping
    image: ping:tar
    ports:
      - target: 7417
        published: 7417
    volumes:
      - "${PWD}/data:/home/data"
    env_file:
      - .env
    restart:
      on-failure
