
GET http://localhost/api/v1/friends/zineb
[
    {
        "username": "zineb",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar179.png",
        "stat": "accepted"
    },
    {
        "username": "ayoub",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar175.png",
        "stat": "accepted"
    },
    {
        "username": "khalid",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar115.png",
        "stat": "accepted"
    }
]

GET http://localhost/api/v1/friends/u/oub
[
    {
        "username": "ayoub",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar175.png"
    }
]



POST http://localhost/api/v1/friends/check
{
    "to": "fatima"
}

{
    "message": "you are friends with benifits"
}


POST http://localhost/api/v1/friends/add
{
    "to": "fatima"
}


{
    "message": "added successfully"
}

PUT http://localhost/api/v1/friends/accept
{
    "to": "youssef"
}

{
    "message": "accepted successfully"
}


PUT http://localhost/api/v1/friends/accept
{
    "to": "ayoub"
}

{
    "message": "blocked successfully"
}

DELETE http://localhost/api/v1/friends/remove
{
    "to": "youssef"
}

{
    "message": "blocked successfully"
}
