GET http://localhost/api/v1/game/pong/history/reda
[
    {
        "user_id": 1,
        "player_username": "ayoub",
        "player_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar17.png",
        "opponent_username": "furina",
        "opponent_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar197.png",
        "player_score": 4,
        "opponent_score": 4
    },
    {
        "user_id": 10,
        "player_username": "ayoub",
        "player_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar17.png",
        "opponent_username": "reda",
        "opponent_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar100.png",
        "player_score": 1,
        "opponent_score": 7
    }
]

GET http://localhost/api/v1/game/doom/history/imane
[
    {
        "user_id": 8,
        "player_username": "khalid",
        "player_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar70.png",
        "opponent_username": "imane",
        "opponent_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar13.png",
        "winner_username": "imane",
        "game_date": "2025-07-19"
    },
    {
        "user_id": 9,
        "player_username": "imane",
        "player_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar13.png",
        "opponent_username": "ayoub",
        "opponent_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar17.png",
        "winner_username": "imane",
        "game_date": "2025-07-19"
    },
    {
        "user_id": 3,
        "player_username": "fatima",
        "player_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar15.png",
        "opponent_username": "imane",
        "opponent_avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar13.png",
        "winner_username": "imane",
        "game_date": "2025-06-28"
    }
]
GET http://localhost/api/v1/game/pong/leaderboard
[
    {
        "id": 10,
        "username": "reda",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar100.png",
        "winns": 2
    },
    {
        "id": 6,
        "username": "hamza",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar125.png",
        "winns": 2
    },
    {
        "id": 4,
        "username": "youssef",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar75.png",
        "winns": 2
    },
    {
        "id": 1,
        "username": "furina",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar197.png",
        "winns": 2
    },
    {
        "id": 8,
        "username": "khalid",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar70.png",
        "winns": 1
    },
    {
        "id": 7,
        "username": "zineb",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar171.png",
        "winns": 1
    }
]

GET http://localhost/api/v1/game/doom/leaderboard
[
    {
        "id": 9,
        "username": "imane",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar13.png",
        "winns": 3
    },
    {
        "id": 8,
        "username": "khalid",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar70.png",
        "winns": 1
    },
    {
        "id": 7,
        "username": "zineb",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar171.png",
        "winns": 1
    },
    {
        "id": 6,
        "username": "hamza",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar125.png",
        "winns": 1
    },
    {
        "id": 5,
        "username": "salma",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar14.png",
        "winns": 1
    },
    {
        "id": 4,
        "username": "youssef",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar75.png",
        "winns": 1
    },
    {
        "id": 3,
        "username": "fatima",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar15.png",
        "winns": 1
    },
    {
        "id": 1,
        "username": "furina",
        "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar197.png",
        "winns": 1
    }
]
GET http://localhost/api/v1/game/pong/summary/ayoub
{
    "total_games": 2,
    "total_winns": 0,
    "totalTournamentPlayed": 1,
    "totalTournamentWinns": 0
}

GET http://localhost/api/v1/game/doom/summary/reda
{
    "total_games": 0,
    "total_winns": 0
}
GET http://localhost/api/v1/game/tournament/Tournament_1
{
    "Name": "Tournament_1",
    "Date": "2025-07-13",
    "Winner_username": "zineb",
    "Contestants": [
        {
            "username": "fatima",
            "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar15.png",
            "round_level": 0.5
        },
        {
            "username": "hamza",
            "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar125.png",
            "round_level": 0.5
        },
        {
            "username": "furina",
            "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar197.png",
            "round_level": 0.3
        },
        {
            "username": "reda",
            "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar100.png",
            "round_level": 0.5
        },
        {
            "username": "ayoub",
            "avatar_url": "https://res.cloudinary.com/drpmyxx4c/image/upload/v1751976105/avatars/avatar17.png",
            "round_level": 0.4
        }
    ],
    "matches": [
        {
            "user": "imane",
            "opponent": "reda",
            "player_score": 1,
            "opponent_score": 10,
            "date": "2025-07-21"
        },
        {
            "user": "youssef",
            "opponent": "khalid",
            "player_score": 5,
            "opponent_score": 1,
            "date": "2025-07-13"
        }
    ]
}
GET http://localhost/api/v1/game/tournament/history
[
    {
        "tournament_name": "Tournament_3",
        "tournament_date": "2025-07-19",
        "winner_id": 4
    },
    {
        "tournament_name": "Tournament_1",
        "tournament_date": "2025-07-13",
        "winner_id": 7
    },
    {
        "tournament_name": "Tournament_4",
        "tournament_date": "2025-07-13",
        "winner_id": 7
    },
    {
        "tournament_name": "Tournament_2",
        "tournament_date": "2025-07-08",
        "winner_id": 1
    }
]