


│ LoginVerify    │ /(auth)/2fa-authentication/
│ Login          │ /(auth)/add-bio/
│ Login          │ /(auth)/add-profile-picture/
│ ForgotPassword │ /(auth)/forgot-password/
│ Login          │ /(auth)/login/
│ ResetPassword  │ /(auth)/reset-password/
│ SignUp         │ /(auth)/signup/
│ SignUpVerify   │ /(auth)/verify-account/
│ Page           │ /main/(fetchall)/doomhistory/[profile]/
│ Page           │ /main/(fetchall)/doomleaderboard/
│ Page           │ /main/(fetchall)/ponghistory/[profile]/
│ Page           │ /main/(fetchall)/pongleaderboard/
│ Page           │ /main/(fetchall)/tournaments/
│ Page           │ /main/dashboard/[profile]/
│ Chat           │ /main/dashboard/chat/
│ Page           │ /main/dashboard/gameplay/doom/[gid]/[opponent]/
│ Page           │ /main/dashboard/gameplay/local/
│ Page           │ /main/dashboard/gameplay/pong/[gid]/[opponent]/
│ LeaderBoard    │ /main/dashboard/leaderboard/
│ Playground     │ /main/dashboard/playground/
│ Tournament     │ /main/dashboard/tournament/[tournamentname]/
│ Tournament     │ /main/dashboard/tournament/

