/dash
	/
	/board
		/
		/chat
		/friends
		/leaderboard
		/playground
		/gameplay
			/local
			/remote
		/tournament
			/
			/[tournamentname]

GET │ /api/v1/friends/:username
PUT │ /api/v1/friends/accept
POST │ /api/v1/friends/add
PUT │ /api/v1/friends/block
POST │ /api/v1/friends/check
DELETE │ /api/v1/friends/remove
GET │ /api/v1/friends/u/:keyword