{
 "title": "containers dashboards",
 "description": "SAVE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dockerstats_memory_usage_bytes) by (container) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dockerstats_cpu_usage_ratio) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY USAGE FOR EACH CONTAINER",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_bytes  / 1024 / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU USAGE for each Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "dockerstats_cpu_usage_ratio", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "e",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk (10, rate(dockerstats_network_transmitted_bytes[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk (10, rate(dockerstats_network_received_bytes[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}