{
 "title": "pingpong_42",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "UPTIME",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx HTTP Requests per Route",
   "type": "stat",
   "description": "\tShows number of 4xx errors per route on each instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=~\"4..\", instance=\"$instance\"}) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{instance=\"$instance\"}[5m])) by (le, route))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "traffic",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=\"$instance\"}[5m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}