import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-amber-50`}>
				<ul className="flex gap-4">
					<li>
						<Link href="/login">/login</Link>
					</li>
					<li>
						<Link href="/signup">/signup</Link>
					</li>
					<li>
						<Link href="/dash">/dash</Link>
					</li>
					<li>
						<Link href="/verify-account">/verify-account</Link>
					</li>
					<li>
						<Link href="/2fa-authentication">/2fa-authentication</Link>
					</li>
				</ul>
				{children}
			</body>
		</html>
	);
}
