
GET https://localhost:7443/api/auth/ping HTTP/1.1
Content-Type: application/json

###

GET https://localhost:7443/ws/ping HTTP/1.1

###
POST https://localhost:7443/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "otman",
    "pass": "otman"
}

###

POST https://localhost:7443/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username": "otman",
    "email": "otman@gmail.com",
    "pass": "otman"
}

###

POST https://localhost:7443/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "username": "otman"
}

###

POST https://localhost:7443/api/auth/password/get-otp HTTP/1.1
Content-Type: application/json

{
    "email": "ooulcaid.1337@gmail.com"
}

###

POST https://localhost:7443/api/auth/password/verify-otp HTTP/1.1
Content-Type: application/json

{
    "email": "ooulcaid.1337@gmail.com",
    "otp": "091827"
}

###

POST https://localhost:7443/api/auth/refresh HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90bWFuIiwicGFzcyI6Im90bWFuIiwiaWF0IjoxNzQ5ODk1MTg3LCJleHAiOjE3NTUwNzkxODd9.GNtqAmxDj5Rb32R4R4PjlNalsPkO5o377zvL-aA-zgA"
}
