
POST https://localhost:7443/api/user/update HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90bWFuIiwicGFzcyI6Im90bWFuIiwiaWF0IjoxNzQ1NTYzNDg4LCJleHAiOjE3NTA3NDc0ODh9.KjB-dl5JLFbG5335oTRg0azcOfBTdVazrCOY6QblvmM

{
  "filter": { "username": "otman" },
  "data" : {
    "username": "otman",
    "email": "otman@otman",
    "bio": "...loking for internship"
  }
}

###

POST https://localhost:7443/api/user/graphql HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90bWFuIiwicGFzcyI6Im90bWFuIiwiaWF0IjoxNzQ1NTYzNDg4LCJleHAiOjE3NTA3NDc0ODh9.KjB-dl5JLFbG5335oTRg0azcOfBTdVazrCOY6QblvmM
Content-Type: application/json

{
  "fields" : ["username", "avatar", "bio"]
}

###

#get a specific user
POST https://localhost:7443/api/user/filter HTTP/1.1 
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90bWFuIiwicGFzcyI6Im90bWFuIiwiaWF0IjoxNzQ1NTYzNDg4LCJleHAiOjE3NTA3NDc0ODh9.KjB-dl5JLFbG5335oTRg0azcOfBTdVazrCOY6QblvmM
Content-Type: application/json

{
  "filter" : {"username" : "tarikkudesu"},
  "fields" : ["username","email", "avatar"]
}
###

#get all users
GET https://localhost:7443/api/user HTTP/1.1 
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90bWFuIiwicGFzcyI6Im90bWFuIiwiaWF0IjoxNzQ1NTYzNDg4LCJleHAiOjE3NTA3NDc0ODh9.KjB-dl5JLFbG5335oTRg0azcOfBTdVazrCOY6QblvmM

###

POST https://localhost:7443/api/user/delete HTTP/1.1 
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90bWFuIiwicGFzcyI6Im90bWFuIiwiaWF0IjoxNzQ1NTYzNDg4LCJleHAiOjE3NTA3NDc0ODh9.KjB-dl5JLFbG5335oTRg0azcOfBTdVazrCOY6QblvmM
Content-Type: application/json

{
  "filter" : {"username" : "otman"}
}
